on: push
name: ? Deploy website on push
branches:
      - master
jobs:
  web-deploy:
    name: ? Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ? Get latest code
      uses: actions/checkout@v3
    
    - name: ? Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.phxview.online
        username: dev@dev.phxview.online
        password: phxview2024
        protocol: ftps